version: '2'
.catalog:
  name: Harbor
  version: 0.5.0-singlehost-rev0
  description: |
    Enterprise Class Container Registry by VMware
  minimum_rancher_version: v0.59.0
  uuid: harbor-0
  questions:
    - variable: "harborhostname"
      description: "Harbor IP, HOSTNAME or FQDN as used to acces it from the Docker CLI"
      label: "IP/Hostname/FQDN:"
      required: true
      default: myregistry
      type: "string"
    - variable: "harbor_admin_password"
      label: "Harbor password:"
      description: |
        Harbor admin password
      default: Vmware123!
      required: true
      type: "string"
    - variable: "auth_mode"
      label: "AUTH_MODE:"
      description: |
        Auth mode: db_auth or ldap_auth
      default: ldap_auth
      required: false
      type: "string"
    - variable: "ldap_url"
      label: "LDAP_URL:"
      description: |
        LDAP url
      default: 10.22.1.61
      required: false
      type: "string"
    - variable: "ldap_searchdn"
      label: "LDAP_SEARCHDN:"
      description: |
        LDAP admin account
      default: releaseadmin
      required: false
      type: "string"
    - variable: "ldap_search_pwd"
      label: "LDAP_SEARCH_PWD:"
      description: |
        LDAP admin account password
      default: passwd
      required: false
      type: "string"
    - variable: "ldap_basedn"
      label: "LDAP_BASEDN:"
      description: |
        LDAP basedn
      default: passwd
      required: false
      type: "string"
    - variable: "ldap_filter"
      label: "LDAP_FILTER:"
      description: |
        LDAP filter
      default: objectClass=*
      required: false
      type: "string"
    - variable: "ldap_uid"
      label: "LDAP_UID:"
      description: |
        LDAP uid
      default: uid
      required: false
      type: "string"
    - variable: "harborhostlabel"
      label: "Harbor will be deployed on the host with this label (default: harbor-host=true)"
      description: |
        Harbor host label
      default: harbor-host=true
      required: true
      type: "string"
services:
  registry:
    scale: 1
    start_on_create: false
  proxy:
    scale: 1
    start_on_create: false
  jobservice:
    scale: 1
    start_on_create: false
  ui:
    scale: 1
    start_on_create: false
  mysql:
    scale: 1
    start_on_create: false
  harbor-setupwrapper:
    scale: 1
    start_on_create: true
