version: '2'
.catalog:
  name: Harbor
  version: 0.5.0-singlehost-rev0
  description: |
    Enterprise Class Container Registry by VMware
  minimum_rancher_version: v0.59.0
  uuid: harbor-0
  questions:
    - variable: "harborhostname"
      description: "Harbor IP, HOSTNAME or FQDN as used to acces it from the Docker CLI"
      label: "IP/Hostname/FQDN:"
      required: true
      default: myregistry
      type: "string"
    - variable: "harbor_admin_password"
      label: "Harbor password:"
      description: |
        Harbor admin password
      default: harbor12#
      required: true
      type: "string"
    - variable: "auth_mode"
      label: "auth_mode"
      description: |
        ldap_auth or db_auth
      default: ldap_auth
      required: true
      type: "string"
    - variable: "ldap_url"
      label: "ldap_url"
      description: |
        LDAP(AD) server URL
      default: ldap://10.22.1.61
      required: true
      type: "string"
    - variable: "ldap_searchdn"
      label: "ldap_searchdn"
      description: |
        LDAP admin account
      default: releaseadmin 
      required: true
      type: "string"
    - variable: "ldap_search_pwd"
      label: "ldap_search_pwd"
      description: |
        LDAP admin account password
      default: passwd12#
      required: true
      type: "string"
    - variable: "ldap_basedn"
      label: "ldap_basedn"
      description: |
        LDAP BASEDN: dc=skcomms,dc=net
      default: dc=skcomms,dc=net
      required: true
      type: "string"
    - variable: "ldap_filter"
      label: "ldap_filter"
      description: |
        LDAP objectClass: objectClass=person
      default: objectClass=person
      required: true
      type: "string"
    - variable: "ldap_uid"
      label: "ldap_uid"
      description: |
        LDAP uid: sAMAccountName
      default: sAMAccountName
      required: true
      type: "string"
    - variable: "ldap_scope"
      label: "ldap_scope"
      description: |
        LDAP scope: 3
      default: 3
      required: true
      type: "string"      
    - variable: "ui_url_protocol"
      label: "ui_url_protocol"
      description: |
        http or https
      default: http
      required: true
      type: "string"
    - variable: "harborhostlabel"
      label: "Harbor will be deployed on the host with this label (default: harbor-host=true)"
      description: |
        Harbor host label
      default: harbor-host=true
      required: true
      type: "string"  
services:
  registry:
    scale: 1
    start_on_create: false
  proxy:
    scale: 1
    start_on_create: false
  jobservice:
    scale: 1
    start_on_create: false
  ui:
    scale: 1
    start_on_create: false
  mysql:
    scale: 1
    start_on_create: false
  harbor-setupwrapper:
    scale: 1
    start_on_create: true
